version: "3.9"

services:
  web:
    build: .
    container_name: stacktracker-web-supabase
    # Usamos las variables desde el entorno / fichero .env del host
    env_file:
      - .env
    environment:
      # Puedes sobreescribir aquí si quieres valores distintos a los del .env
      # Dejamos DJANGO_DEBUG en True para entorno local, así no exige
      # manifest de staticfiles y se comporta como desarrollo.
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: 0.0.0.0,localhost
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
